# from flask import Blueprint
from .surveyor.notifications import notifications_bp
from .surveyor.attendants_survey import attendants_survey_bp
from .surveyor.tasks_survey import tasks_survey_bp
from .surveyor.demandas import demandas_bp
from .surveyor.customers import customers_bp
from .surveyor.auth_surveyor import auth_surveyor_bp
from .surveyor.users_surveyor import users_surveyor_bp
from .surveyor.vessel import vessel_bp
from .surveyor.cargo import cargo_bp
from .surveyor.cargo_condition import cargo_condition_bp
from .surveyor.cargo_inspection import cargo_inspection_bp
from .surveyor.lashing_cargo import lashing_cargo_bp
from .surveyor.lashing_material import lashing_material_bp
from .surveyor.cargo_storage import cargo_storage_bp
from .surveyor.lifting_operation import lifting_operation_bp
from .surveyor.lifting_material import lifting_material_bp
from .surveyor.tarefas import tarefas_bp
from .surveyor.preliminary_checklist import checklist_bp
from .surveyor.offline_provider import offiline_bp
from .surveyor.auth_customer import auth_customer_bp
from .surveyor.users_customer import users_customer_bp
from .surveyor.notifications_customer import notifications_customer_bp
from .surveyor.lifting_inspection import lifting_inspection_bp
from .surveyor.lashing_inspection import lashing_inspection_bp
from .surveyor.statement_of_facts import statement_of_facts_bp
from .surveyor.relations import relation_bp
from .surveyor.clients import clients_bp
from .surveyor.health import health_bp
from .surveyor.survey_pdf import survey_pdf_bp
from .surveyor.settings import settings_bp
from .financeiro.medicoes import medicoes_bp
from .financeiro.nota_fiscal import nota_fiscal_bp
from .financeiro.pdf_extraction import pdf_extraction_bp